//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioConectorFE.IntegradorEstelaEstado {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dbnet.cl", ConfigurationName="IntegradorEstelaEstado.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruc del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ConsultaEstado", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponse ConsultaEstado(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ConsultaEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponse> ConsultaEstadoAsync(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruc del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ConsultaEstadoGuia", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponse ConsultaEstadoGuia(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ConsultaEstadoGuia", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponse> ConsultaEstadoGuiaAsync(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruc del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ActualizaEstadoDoc", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponse ActualizaEstadoDoc(ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ActualizaEstadoDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponse> ActualizaEstadoDocAsync(ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ruc del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ConsultaTED", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponse ConsultaTED(ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ConsultaTED", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponse> ConsultaTEDAsync(ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaEstado", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequestBody Body;
        
        public ConsultaEstadoRequest() {
        }
        
        public ConsultaEstadoRequest(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ConsultaEstadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tipo_docu;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int foli_inte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serie_inte;
        
        public ConsultaEstadoRequestBody() {
        }
        
        public ConsultaEstadoRequestBody(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            this.ruc = ruc;
            this.tipo_docu = tipo_docu;
            this.foli_inte = foli_inte;
            this.serie_inte = serie_inte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaEstadoResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponseBody Body;
        
        public ConsultaEstadoResponse() {
        }
        
        public ConsultaEstadoResponse(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ConsultaEstadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultaEstadoResult;
        
        public ConsultaEstadoResponseBody() {
        }
        
        public ConsultaEstadoResponseBody(string ConsultaEstadoResult) {
            this.ConsultaEstadoResult = ConsultaEstadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEstadoGuiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaEstadoGuia", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequestBody Body;
        
        public ConsultaEstadoGuiaRequest() {
        }
        
        public ConsultaEstadoGuiaRequest(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ConsultaEstadoGuiaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tipo_docu;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int foli_inte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serie_inte;
        
        public ConsultaEstadoGuiaRequestBody() {
        }
        
        public ConsultaEstadoGuiaRequestBody(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            this.ruc = ruc;
            this.tipo_docu = tipo_docu;
            this.foli_inte = foli_inte;
            this.serie_inte = serie_inte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEstadoGuiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaEstadoGuiaResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponseBody Body;
        
        public ConsultaEstadoGuiaResponse() {
        }
        
        public ConsultaEstadoGuiaResponse(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ConsultaEstadoGuiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultaEstadoGuiaResult;
        
        public ConsultaEstadoGuiaResponseBody() {
        }
        
        public ConsultaEstadoGuiaResponseBody(string ConsultaEstadoGuiaResult) {
            this.ConsultaEstadoGuiaResult = ConsultaEstadoGuiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaEstadoDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizaEstadoDoc", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequestBody Body;
        
        public ActualizaEstadoDocRequest() {
        }
        
        public ActualizaEstadoDocRequest(ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ActualizaEstadoDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CodiEmpr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int tipo_docu;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int foli_inte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serie_inte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Estado;
        
        public ActualizaEstadoDocRequestBody() {
        }
        
        public ActualizaEstadoDocRequestBody(string ruc, int CodiEmpr, int tipo_docu, int foli_inte, string serie_inte, string Estado) {
            this.ruc = ruc;
            this.CodiEmpr = CodiEmpr;
            this.tipo_docu = tipo_docu;
            this.foli_inte = foli_inte;
            this.serie_inte = serie_inte;
            this.Estado = Estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaEstadoDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizaEstadoDocResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponseBody Body;
        
        public ActualizaEstadoDocResponse() {
        }
        
        public ActualizaEstadoDocResponse(ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ActualizaEstadoDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ActualizaEstadoDocResult;
        
        public ActualizaEstadoDocResponseBody() {
        }
        
        public ActualizaEstadoDocResponseBody(int ActualizaEstadoDocResult) {
            this.ActualizaEstadoDocResult = ActualizaEstadoDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTEDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaTED", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequestBody Body;
        
        public ConsultaTEDRequest() {
        }
        
        public ConsultaTEDRequest(ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ConsultaTEDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ruc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tipo_docu;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int foli_inte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serie_inte;
        
        public ConsultaTEDRequestBody() {
        }
        
        public ConsultaTEDRequestBody(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            this.ruc = ruc;
            this.tipo_docu = tipo_docu;
            this.foli_inte = foli_inte;
            this.serie_inte = serie_inte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTEDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaTEDResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponseBody Body;
        
        public ConsultaTEDResponse() {
        }
        
        public ConsultaTEDResponse(ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ConsultaTEDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultaTEDResult;
        
        public ConsultaTEDResponseBody() {
        }
        
        public ConsultaTEDResponseBody(string ConsultaTEDResult) {
            this.ConsultaTEDResult = ConsultaTEDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ServicioConectorFE.IntegradorEstelaEstado.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ServicioConectorFE.IntegradorEstelaEstado.Service1Soap>, ServicioConectorFE.IntegradorEstelaEstado.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponse ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ConsultaEstado(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest request) {
            return base.Channel.ConsultaEstado(request);
        }
        
        public string ConsultaEstado(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponse retVal = ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ConsultaEstado(inValue);
            return retVal.Body.ConsultaEstadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponse> ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ConsultaEstadoAsync(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest request) {
            return base.Channel.ConsultaEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoResponse> ConsultaEstadoAsync(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            return ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ConsultaEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponse ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ConsultaEstadoGuia(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest request) {
            return base.Channel.ConsultaEstadoGuia(request);
        }
        
        public string ConsultaEstadoGuia(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponse retVal = ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ConsultaEstadoGuia(inValue);
            return retVal.Body.ConsultaEstadoGuiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponse> ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ConsultaEstadoGuiaAsync(ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest request) {
            return base.Channel.ConsultaEstadoGuiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaResponse> ConsultaEstadoGuiaAsync(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaEstadoGuiaRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            return ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ConsultaEstadoGuiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponse ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ActualizaEstadoDoc(ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest request) {
            return base.Channel.ActualizaEstadoDoc(request);
        }
        
        public int ActualizaEstadoDoc(string ruc, int CodiEmpr, int tipo_docu, int foli_inte, string serie_inte, string Estado) {
            ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.CodiEmpr = CodiEmpr;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            inValue.Body.Estado = Estado;
            ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponse retVal = ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ActualizaEstadoDoc(inValue);
            return retVal.Body.ActualizaEstadoDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponse> ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ActualizaEstadoDocAsync(ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest request) {
            return base.Channel.ActualizaEstadoDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocResponse> ActualizaEstadoDocAsync(string ruc, int CodiEmpr, int tipo_docu, int foli_inte, string serie_inte, string Estado) {
            ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ActualizaEstadoDocRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.CodiEmpr = CodiEmpr;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            inValue.Body.Estado = Estado;
            return ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ActualizaEstadoDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponse ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ConsultaTED(ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest request) {
            return base.Channel.ConsultaTED(request);
        }
        
        public string ConsultaTED(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponse retVal = ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ConsultaTED(inValue);
            return retVal.Body.ConsultaTEDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponse> ServicioConectorFE.IntegradorEstelaEstado.Service1Soap.ConsultaTEDAsync(ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest request) {
            return base.Channel.ConsultaTEDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDResponse> ConsultaTEDAsync(string ruc, int tipo_docu, int foli_inte, string serie_inte) {
            ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest inValue = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaEstado.ConsultaTEDRequestBody();
            inValue.Body.ruc = ruc;
            inValue.Body.tipo_docu = tipo_docu;
            inValue.Body.foli_inte = foli_inte;
            inValue.Body.serie_inte = serie_inte;
            return ((ServicioConectorFE.IntegradorEstelaEstado.Service1Soap)(this)).ConsultaTEDAsync(inValue);
        }
    }
}
