//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioConectorFE.IntegradorPaperless {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.online.asp.core.paperless.cl", ConfigurationName="IntegradorPaperless.OnlinePortType")]
    public interface OnlinePortType {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineEventos", ReplyAction="urn:OnlineEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineEventosResponse OnlineEventos(ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineEventos", ReplyAction="urn:OnlineEventosResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineEventosResponse> OnlineEventosAsync(ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Consult", ReplyAction="urn:ConsultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.ConsultResponse Consult(ServicioConectorFE.IntegradorPaperless.ConsultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Consult", ReplyAction="urn:ConsultResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.ConsultResponse> ConsultAsync(ServicioConectorFE.IntegradorPaperless.ConsultRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineConsultaEstado", ReplyAction="urn:OnlineConsultaEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoResponse OnlineConsultaEstado(ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineConsultaEstado", ReplyAction="urn:OnlineConsultaEstadoResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoResponse> OnlineConsultaEstadoAsync(ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAdjuntosRecibidos", ReplyAction="urn:listarAdjuntosRecibidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosResponse listarAdjuntosRecibidos(ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAdjuntosRecibidos", ReplyAction="urn:listarAdjuntosRecibidosResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosResponse> listarAdjuntosRecibidosAsync(ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultaInformeReversiones", ReplyAction="urn:ConsultaInformeReversionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesResponse ConsultaInformeReversiones(ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultaInformeReversiones", ReplyAction="urn:ConsultaInformeReversionesResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesResponse> ConsultaInformeReversionesAsync(ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:CargaInformeBajas", ReplyAction="urn:CargaInformeBajasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.CargaInformeBajasResponse CargaInformeBajas(ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CargaInformeBajas", ReplyAction="urn:CargaInformeBajasResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.CargaInformeBajasResponse> CargaInformeBajasAsync(ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineRecoveryResponse OnlineRecovery(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryResponse> OnlineRecoveryAsync(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:InformeResBoletasDiario", ReplyAction="urn:InformeResBoletasDiarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioResponse InformeResBoletasDiario(ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:InformeResBoletasDiario", ReplyAction="urn:InformeResBoletasDiarioResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioResponse> InformeResBoletasDiarioAsync(ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListResponse OnlineRecoveryRecList(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListResponse> OnlineRecoveryRecListAsync(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GenInformeReversiones", ReplyAction="urn:GenInformeReversionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.GenInformeReversionesResponse GenInformeReversiones(ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GenInformeReversiones", ReplyAction="urn:GenInformeReversionesResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.GenInformeReversionesResponse> GenInformeReversionesAsync(ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineARC", ReplyAction="urn:OnlineARCResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineARCResponse OnlineARC(ServicioConectorFE.IntegradorPaperless.OnlineARCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineARC", ReplyAction="urn:OnlineARCResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineARCResponse> OnlineARCAsync(ServicioConectorFE.IntegradorPaperless.OnlineARCRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineGenerationResponse OnlineGeneration(ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineGenerationResponse> OnlineGenerationAsync(ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecResponse OnlineRecoveryRec(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecResponse> OnlineRecoveryRecAsync(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddDocInfo", ReplyAction="urn:AddDocInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServicioConectorFE.IntegradorPaperless.AddDocInfoResponse AddDocInfo(ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddDocInfo", ReplyAction="urn:AddDocInfoResponse")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.AddDocInfoResponse> AddDocInfoAsync(ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineEventos", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        public OnlineEventosRequest() {
        }
        
        public OnlineEventosRequest(string ruc, string login, string clave, string docTxt) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineEventosResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineEventosResponse() {
        }
        
        public OnlineEventosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consult", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @params;
        
        public ConsultRequest() {
        }
        
        public ConsultRequest(string ruc, string login, string clave, string @params) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConsultResponse() {
        }
        
        public ConsultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineConsultaEstado", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineConsultaEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int estado;
        
        public OnlineConsultaEstadoRequest() {
        }
        
        public OnlineConsultaEstadoRequest(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucReceptor = rucReceptor;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineConsultaEstadoResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineConsultaEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineConsultaEstadoResponse() {
        }
        
        public OnlineConsultaEstadoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdjuntosRecibidos", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class listarAdjuntosRecibidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        public listarAdjuntosRecibidosRequest() {
        }
        
        public listarAdjuntosRecibidosRequest(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDocumento = tipoDocumento;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdjuntosRecibidosResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class listarAdjuntosRecibidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public listarAdjuntosRecibidosResponse() {
        }
        
        public listarAdjuntosRecibidosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformeReversiones", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultaInformeReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int idRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numTicketSunat;
        
        public ConsultaInformeReversionesRequest() {
        }
        
        public ConsultaInformeReversionesRequest(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.idRegistro = idRegistro;
            this.numTicketSunat = numTicketSunat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformeReversionesResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultaInformeReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConsultaInformeReversionesResponse() {
        }
        
        public ConsultaInformeReversionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargaInformeBajas", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class CargaInformeBajasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string periodo;
        
        public CargaInformeBajasRequest() {
        }
        
        public CargaInformeBajasRequest(string ruc, string login, string clave, string docTxt, string periodo) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargaInformeBajasResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class CargaInformeBajasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public CargaInformeBajasResponse() {
        }
        
        public CargaInformeBajasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecovery", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        public int tipoRetorno;
        
        public OnlineRecoveryRequest() {
        }
        
        public OnlineRecoveryRequest(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryResponse() {
        }
        
        public OnlineRecoveryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InformeResBoletasDiario", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class InformeResBoletasDiarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaInforme;
        
        public InformeResBoletasDiarioRequest() {
        }
        
        public InformeResBoletasDiarioRequest(string ruc, string login, string clave, string fechaInforme) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.fechaInforme = fechaInforme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InformeResBoletasDiarioResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class InformeResBoletasDiarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public InformeResBoletasDiarioResponse() {
        }
        
        public InformeResBoletasDiarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecList", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fecha;
        
        public OnlineRecoveryRecListRequest() {
        }
        
        public OnlineRecoveryRecListRequest(string ruc, string login, string clave, string fecha) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecListResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecListResponse() {
        }
        
        public OnlineRecoveryRecListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInformeReversiones", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class GenInformeReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tpoGen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tramaTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string periodo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public bool envioSUNAT;
        
        public GenInformeReversionesRequest() {
        }
        
        public GenInformeReversionesRequest(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tpoGen = tpoGen;
            this.tramaTxt = tramaTxt;
            this.periodo = periodo;
            this.envioSUNAT = envioSUNAT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInformeReversionesResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class GenInformeReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GenInformeReversionesResponse() {
        }
        
        public GenInformeReversionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineARC", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineARCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        public OnlineARCRequest() {
        }
        
        public OnlineARCRequest(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.estado = estado;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineARCResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineARCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineARCResponse() {
        }
        
        public OnlineARCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGeneration", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoFoliacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        public int tipoRetorno;
        
        public OnlineGenerationRequest() {
        }
        
        public OnlineGenerationRequest(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
            this.tipoFoliacion = tipoFoliacion;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineGenerationResponse() {
        }
        
        public OnlineGenerationResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRec", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int tipoRetorno;
        
        public OnlineRecoveryRecRequest() {
        }
        
        public OnlineRecoveryRecRequest(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecResponse() {
        }
        
        public OnlineRecoveryRecResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocInfo", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class AddDocInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string infoAdicional;
        
        public AddDocInfoRequest() {
        }
        
        public AddDocInfoRequest(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.infoAdicional = infoAdicional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocInfoResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class AddDocInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public AddDocInfoResponse() {
        }
        
        public AddDocInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlinePortTypeChannel : ServicioConectorFE.IntegradorPaperless.OnlinePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlinePortTypeClient : System.ServiceModel.ClientBase<ServicioConectorFE.IntegradorPaperless.OnlinePortType>, ServicioConectorFE.IntegradorPaperless.OnlinePortType {
        
        public OnlinePortTypeClient() {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineEventosResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineEventos(ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest request) {
            return base.Channel.OnlineEventos(request);
        }
        
        public string OnlineEventos(string ruc, string login, string clave, string docTxt) {
            ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            ServicioConectorFE.IntegradorPaperless.OnlineEventosResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineEventosResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineEventosAsync(ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest request) {
            return base.Channel.OnlineEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineEventosResponse> OnlineEventosAsync(string ruc, string login, string clave, string docTxt) {
            ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineEventosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.ConsultResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.Consult(ServicioConectorFE.IntegradorPaperless.ConsultRequest request) {
            return base.Channel.Consult(request);
        }
        
        public string Consult(string ruc, string login, string clave, string @params) {
            ServicioConectorFE.IntegradorPaperless.ConsultRequest inValue = new ServicioConectorFE.IntegradorPaperless.ConsultRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.@params = @params;
            ServicioConectorFE.IntegradorPaperless.ConsultResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).Consult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.ConsultResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.ConsultAsync(ServicioConectorFE.IntegradorPaperless.ConsultRequest request) {
            return base.Channel.ConsultAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.ConsultResponse> ConsultAsync(string ruc, string login, string clave, string @params) {
            ServicioConectorFE.IntegradorPaperless.ConsultRequest inValue = new ServicioConectorFE.IntegradorPaperless.ConsultRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.@params = @params;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).ConsultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineConsultaEstado(ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest request) {
            return base.Channel.OnlineConsultaEstado(request);
        }
        
        public string OnlineConsultaEstado(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucReceptor = rucReceptor;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineConsultaEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineConsultaEstadoAsync(ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest request) {
            return base.Channel.OnlineConsultaEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoResponse> OnlineConsultaEstadoAsync(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineConsultaEstadoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucReceptor = rucReceptor;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineConsultaEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.listarAdjuntosRecibidos(ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest request) {
            return base.Channel.listarAdjuntosRecibidos(request);
        }
        
        public string listarAdjuntosRecibidos(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest inValue = new ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDocumento = tipoDocumento;
            inValue.folio = folio;
            ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).listarAdjuntosRecibidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.listarAdjuntosRecibidosAsync(ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest request) {
            return base.Channel.listarAdjuntosRecibidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosResponse> listarAdjuntosRecibidosAsync(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest inValue = new ServicioConectorFE.IntegradorPaperless.listarAdjuntosRecibidosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDocumento = tipoDocumento;
            inValue.folio = folio;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).listarAdjuntosRecibidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.ConsultaInformeReversiones(ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest request) {
            return base.Channel.ConsultaInformeReversiones(request);
        }
        
        public string ConsultaInformeReversiones(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest inValue = new ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.idRegistro = idRegistro;
            inValue.numTicketSunat = numTicketSunat;
            ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).ConsultaInformeReversiones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.ConsultaInformeReversionesAsync(ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest request) {
            return base.Channel.ConsultaInformeReversionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesResponse> ConsultaInformeReversionesAsync(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest inValue = new ServicioConectorFE.IntegradorPaperless.ConsultaInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.idRegistro = idRegistro;
            inValue.numTicketSunat = numTicketSunat;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).ConsultaInformeReversionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.CargaInformeBajasResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.CargaInformeBajas(ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest request) {
            return base.Channel.CargaInformeBajas(request);
        }
        
        public string CargaInformeBajas(string ruc, string login, string clave, string docTxt, string periodo) {
            ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest inValue = new ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.periodo = periodo;
            ServicioConectorFE.IntegradorPaperless.CargaInformeBajasResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).CargaInformeBajas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.CargaInformeBajasResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.CargaInformeBajasAsync(ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest request) {
            return base.Channel.CargaInformeBajasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.CargaInformeBajasResponse> CargaInformeBajasAsync(string ruc, string login, string clave, string docTxt, string periodo) {
            ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest inValue = new ServicioConectorFE.IntegradorPaperless.CargaInformeBajasRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.periodo = periodo;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).CargaInformeBajasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineRecoveryResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineRecovery(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecovery(request);
        }
        
        public string OnlineRecovery(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineRecovery(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineRecoveryAsync(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecoveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryResponse> OnlineRecoveryAsync(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineRecoveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.InformeResBoletasDiario(ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest request) {
            return base.Channel.InformeResBoletasDiario(request);
        }
        
        public string InformeResBoletasDiario(string ruc, string login, string clave, string fechaInforme) {
            ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest inValue = new ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fechaInforme = fechaInforme;
            ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).InformeResBoletasDiario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.InformeResBoletasDiarioAsync(ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest request) {
            return base.Channel.InformeResBoletasDiarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioResponse> InformeResBoletasDiarioAsync(string ruc, string login, string clave, string fechaInforme) {
            ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest inValue = new ServicioConectorFE.IntegradorPaperless.InformeResBoletasDiarioRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fechaInforme = fechaInforme;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).InformeResBoletasDiarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineRecoveryRecList(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecList(request);
        }
        
        public string OnlineRecoveryRecList(string ruc, string login, string clave, string fecha) {
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fecha = fecha;
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineRecoveryRecList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineRecoveryRecListAsync(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListResponse> OnlineRecoveryRecListAsync(string ruc, string login, string clave, string fecha) {
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecListRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fecha = fecha;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineRecoveryRecListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.GenInformeReversionesResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.GenInformeReversiones(ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest request) {
            return base.Channel.GenInformeReversiones(request);
        }
        
        public string GenInformeReversiones(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest inValue = new ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tpoGen = tpoGen;
            inValue.tramaTxt = tramaTxt;
            inValue.periodo = periodo;
            inValue.envioSUNAT = envioSUNAT;
            ServicioConectorFE.IntegradorPaperless.GenInformeReversionesResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).GenInformeReversiones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.GenInformeReversionesResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.GenInformeReversionesAsync(ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest request) {
            return base.Channel.GenInformeReversionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.GenInformeReversionesResponse> GenInformeReversionesAsync(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest inValue = new ServicioConectorFE.IntegradorPaperless.GenInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tpoGen = tpoGen;
            inValue.tramaTxt = tramaTxt;
            inValue.periodo = periodo;
            inValue.envioSUNAT = envioSUNAT;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).GenInformeReversionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineARCResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineARC(ServicioConectorFE.IntegradorPaperless.OnlineARCRequest request) {
            return base.Channel.OnlineARC(request);
        }
        
        public string OnlineARC(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            ServicioConectorFE.IntegradorPaperless.OnlineARCRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineARCRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.estado = estado;
            inValue.version = version;
            ServicioConectorFE.IntegradorPaperless.OnlineARCResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineARC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineARCResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineARCAsync(ServicioConectorFE.IntegradorPaperless.OnlineARCRequest request) {
            return base.Channel.OnlineARCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineARCResponse> OnlineARCAsync(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            ServicioConectorFE.IntegradorPaperless.OnlineARCRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineARCRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.estado = estado;
            inValue.version = version;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineARCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineGenerationResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineGeneration(ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest request) {
            return base.Channel.OnlineGeneration(request);
        }
        
        public string OnlineGeneration(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.tipoFoliacion = tipoFoliacion;
            inValue.tipoRetorno = tipoRetorno;
            ServicioConectorFE.IntegradorPaperless.OnlineGenerationResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineGeneration(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineGenerationResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineGenerationAsync(ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest request) {
            return base.Channel.OnlineGenerationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineGenerationResponse> OnlineGenerationAsync(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineGenerationRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.tipoFoliacion = tipoFoliacion;
            inValue.tipoRetorno = tipoRetorno;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineGenerationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineRecoveryRec(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRec(request);
        }
        
        public string OnlineRecoveryRec(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineRecoveryRec(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.OnlineRecoveryRecAsync(ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRecAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecResponse> OnlineRecoveryRecAsync(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest inValue = new ServicioConectorFE.IntegradorPaperless.OnlineRecoveryRecRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).OnlineRecoveryRecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorPaperless.AddDocInfoResponse ServicioConectorFE.IntegradorPaperless.OnlinePortType.AddDocInfo(ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest request) {
            return base.Channel.AddDocInfo(request);
        }
        
        public string AddDocInfo(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest inValue = new ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.infoAdicional = infoAdicional;
            ServicioConectorFE.IntegradorPaperless.AddDocInfoResponse retVal = ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).AddDocInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.AddDocInfoResponse> ServicioConectorFE.IntegradorPaperless.OnlinePortType.AddDocInfoAsync(ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest request) {
            return base.Channel.AddDocInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorPaperless.AddDocInfoResponse> AddDocInfoAsync(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest inValue = new ServicioConectorFE.IntegradorPaperless.AddDocInfoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.infoAdicional = infoAdicional;
            return ((ServicioConectorFE.IntegradorPaperless.OnlinePortType)(this)).AddDocInfoAsync(inValue);
        }
    }
}
