//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioConectorFE.IntegradorEstelaAdjunto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.dbnet.cl", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dbnet.cl", ConfigurationName="IntegradorEstelaAdjunto.consultaDocumentosPeruSoap")]
    public interface consultaDocumentosPeruSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _ruttEmpr del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getDocumentoPDF", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponse getDocumentoPDF(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getDocumentoPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponse> getDocumentoPDFAsync(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _ruttEmpr del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getDocumentoXML", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponse getDocumentoXML(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getDocumentoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponse> getDocumentoXMLAsync(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _ruttEmpr del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getDocumentoCDR", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponse getDocumentoCDR(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/getDocumentoCDR", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponse> getDocumentoCDRAsync(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtnerVersionResult del espacio de nombres http://www.dbnet.cl no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ObtnerVersion", ReplyAction="*")]
        ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponse ObtnerVersion(ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dbnet.cl/ObtnerVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponse> ObtnerVersionAsync(ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoPDF", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequestBody Body;
        
        public getDocumentoPDFRequest() {
        }
        
        public getDocumentoPDFRequest(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class getDocumentoPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _ruttEmpr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _folioDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _tipoDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _serieInte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _fechaDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _monTotal;
        
        public getDocumentoPDFRequestBody() {
        }
        
        public getDocumentoPDFRequestBody(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            this._ruttEmpr = _ruttEmpr;
            this._folioDTE = _folioDTE;
            this._tipoDTE = _tipoDTE;
            this._serieInte = _serieInte;
            this._fechaDTE = _fechaDTE;
            this._monTotal = _monTotal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoPDFResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponseBody Body;
        
        public getDocumentoPDFResponse() {
        }
        
        public getDocumentoPDFResponse(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class getDocumentoPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoPDFResult;
        
        public getDocumentoPDFResponseBody() {
        }
        
        public getDocumentoPDFResponseBody(ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoPDFResult) {
            this.getDocumentoPDFResult = getDocumentoPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoXML", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequestBody Body;
        
        public getDocumentoXMLRequest() {
        }
        
        public getDocumentoXMLRequest(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class getDocumentoXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _ruttEmpr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _folioDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _tipoDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _serieInte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _fechaDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _monTotal;
        
        public getDocumentoXMLRequestBody() {
        }
        
        public getDocumentoXMLRequestBody(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            this._ruttEmpr = _ruttEmpr;
            this._folioDTE = _folioDTE;
            this._tipoDTE = _tipoDTE;
            this._serieInte = _serieInte;
            this._fechaDTE = _fechaDTE;
            this._monTotal = _monTotal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoXMLResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponseBody Body;
        
        public getDocumentoXMLResponse() {
        }
        
        public getDocumentoXMLResponse(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class getDocumentoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoXMLResult;
        
        public getDocumentoXMLResponseBody() {
        }
        
        public getDocumentoXMLResponseBody(ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoXMLResult) {
            this.getDocumentoXMLResult = getDocumentoXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoCDRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoCDR", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequestBody Body;
        
        public getDocumentoCDRRequest() {
        }
        
        public getDocumentoCDRRequest(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class getDocumentoCDRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _ruttEmpr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _folioDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _tipoDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _serieInte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _fechaDTE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _monTotal;
        
        public getDocumentoCDRRequestBody() {
        }
        
        public getDocumentoCDRRequestBody(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            this._ruttEmpr = _ruttEmpr;
            this._folioDTE = _folioDTE;
            this._tipoDTE = _tipoDTE;
            this._serieInte = _serieInte;
            this._fechaDTE = _fechaDTE;
            this._monTotal = _monTotal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentoCDRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentoCDRResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponseBody Body;
        
        public getDocumentoCDRResponse() {
        }
        
        public getDocumentoCDRResponse(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class getDocumentoCDRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoCDRResult;
        
        public getDocumentoCDRResponseBody() {
        }
        
        public getDocumentoCDRResponseBody(ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoCDRResult) {
            this.getDocumentoCDRResult = getDocumentoCDRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtnerVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtnerVersion", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequestBody Body;
        
        public ObtnerVersionRequest() {
        }
        
        public ObtnerVersionRequest(ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtnerVersionRequestBody {
        
        public ObtnerVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtnerVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtnerVersionResponse", Namespace="http://www.dbnet.cl", Order=0)]
        public ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponseBody Body;
        
        public ObtnerVersionResponse() {
        }
        
        public ObtnerVersionResponse(ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dbnet.cl")]
    public partial class ObtnerVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtnerVersionResult;
        
        public ObtnerVersionResponseBody() {
        }
        
        public ObtnerVersionResponseBody(string ObtnerVersionResult) {
            this.ObtnerVersionResult = ObtnerVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface consultaDocumentosPeruSoapChannel : ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class consultaDocumentosPeruSoapClient : System.ServiceModel.ClientBase<ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap>, ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap {
        
        public consultaDocumentosPeruSoapClient() {
        }
        
        public consultaDocumentosPeruSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public consultaDocumentosPeruSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultaDocumentosPeruSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultaDocumentosPeruSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponse ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.getDocumentoPDF(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest request) {
            return base.Channel.getDocumentoPDF(request);
        }
        
        public ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoPDF(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequestBody();
            inValue.Body._ruttEmpr = _ruttEmpr;
            inValue.Body._folioDTE = _folioDTE;
            inValue.Body._tipoDTE = _tipoDTE;
            inValue.Body._serieInte = _serieInte;
            inValue.Body._fechaDTE = _fechaDTE;
            inValue.Body._monTotal = _monTotal;
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponse retVal = ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).getDocumentoPDF(inValue);
            return retVal.Body.getDocumentoPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponse> ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.getDocumentoPDFAsync(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest request) {
            return base.Channel.getDocumentoPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFResponse> getDocumentoPDFAsync(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoPDFRequestBody();
            inValue.Body._ruttEmpr = _ruttEmpr;
            inValue.Body._folioDTE = _folioDTE;
            inValue.Body._tipoDTE = _tipoDTE;
            inValue.Body._serieInte = _serieInte;
            inValue.Body._fechaDTE = _fechaDTE;
            inValue.Body._monTotal = _monTotal;
            return ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).getDocumentoPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponse ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.getDocumentoXML(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest request) {
            return base.Channel.getDocumentoXML(request);
        }
        
        public ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoXML(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequestBody();
            inValue.Body._ruttEmpr = _ruttEmpr;
            inValue.Body._folioDTE = _folioDTE;
            inValue.Body._tipoDTE = _tipoDTE;
            inValue.Body._serieInte = _serieInte;
            inValue.Body._fechaDTE = _fechaDTE;
            inValue.Body._monTotal = _monTotal;
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponse retVal = ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).getDocumentoXML(inValue);
            return retVal.Body.getDocumentoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponse> ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.getDocumentoXMLAsync(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest request) {
            return base.Channel.getDocumentoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLResponse> getDocumentoXMLAsync(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoXMLRequestBody();
            inValue.Body._ruttEmpr = _ruttEmpr;
            inValue.Body._folioDTE = _folioDTE;
            inValue.Body._tipoDTE = _tipoDTE;
            inValue.Body._serieInte = _serieInte;
            inValue.Body._fechaDTE = _fechaDTE;
            inValue.Body._monTotal = _monTotal;
            return ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).getDocumentoXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponse ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.getDocumentoCDR(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest request) {
            return base.Channel.getDocumentoCDR(request);
        }
        
        public ServicioConectorFE.IntegradorEstelaAdjunto.ArrayOfString getDocumentoCDR(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequestBody();
            inValue.Body._ruttEmpr = _ruttEmpr;
            inValue.Body._folioDTE = _folioDTE;
            inValue.Body._tipoDTE = _tipoDTE;
            inValue.Body._serieInte = _serieInte;
            inValue.Body._fechaDTE = _fechaDTE;
            inValue.Body._monTotal = _monTotal;
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponse retVal = ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).getDocumentoCDR(inValue);
            return retVal.Body.getDocumentoCDRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponse> ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.getDocumentoCDRAsync(ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest request) {
            return base.Channel.getDocumentoCDRAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRResponse> getDocumentoCDRAsync(string _ruttEmpr, string _folioDTE, string _tipoDTE, string _serieInte, string _fechaDTE, string _monTotal) {
            ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.getDocumentoCDRRequestBody();
            inValue.Body._ruttEmpr = _ruttEmpr;
            inValue.Body._folioDTE = _folioDTE;
            inValue.Body._tipoDTE = _tipoDTE;
            inValue.Body._serieInte = _serieInte;
            inValue.Body._fechaDTE = _fechaDTE;
            inValue.Body._monTotal = _monTotal;
            return ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).getDocumentoCDRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponse ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.ObtnerVersion(ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest request) {
            return base.Channel.ObtnerVersion(request);
        }
        
        public string ObtnerVersion() {
            ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequestBody();
            ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponse retVal = ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).ObtnerVersion(inValue);
            return retVal.Body.ObtnerVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponse> ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap.ObtnerVersionAsync(ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest request) {
            return base.Channel.ObtnerVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionResponse> ObtnerVersionAsync() {
            ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest inValue = new ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequest();
            inValue.Body = new ServicioConectorFE.IntegradorEstelaAdjunto.ObtnerVersionRequestBody();
            return ((ServicioConectorFE.IntegradorEstelaAdjunto.consultaDocumentosPeruSoap)(this)).ObtnerVersionAsync(inValue);
        }
    }
}
