//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioConectorFE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServicioConectorFE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROCEDURE &quot;EXX_ActualizarEstadoFE&quot; 
        ///(
        /// IN DocEntry INT,
        /// IN ObjectType varchar(5),
        /// IN MensajeError CLOB,
        /// IN Estado varchar(150)
        ///) 
        ///LANGUAGE SQLSCRIPT 
        ///AS 
        ///BEGIN
        /// DECLARE EstadoFE VARCHAR(10);
        /// 
        /// SELECT 
        /// (CASE 
        ///  WHEN Estado=&apos;AC_03&apos; THEN &apos;02&apos;
        ///  WHEN Estado=&apos;RC_05&apos; THEN &apos;03&apos;
        ///  WHEN Estado=&apos;PE_02&apos; THEN &apos;01&apos;
        ///  WHEN Estado=&apos;01&apos; THEN &apos;01&apos;
        ///  WHEN Estado=&apos;02&apos; THEN &apos;02&apos;
        ///  WHEN Estado=&apos;03&apos; THEN &apos;03&apos;
        ///  WHEN Estado=&apos;04&apos; THEN &apos;04&apos;
        ///  ELSE &apos;00&apos;
        ///  END )into  EstadoFE
        /// FROM dummy;
        /// 
        /// IF ObjectTyp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EXX_ActualizarEstadoFE {
            get {
                return ResourceManager.GetString("EXX_ActualizarEstadoFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROCEDURE &quot;EXX_COMPROBANTES_ELECTRONICOS&quot;
        ///(
        /// IN Fecha1 date,
        /// IN fecha2 date,
        /// IN tipodoc nvarchar(500),
        /// IN estado nvarchar(5)
        ///) 
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN 
        ///
        /// SELECT  * ,CURRENT_DATE FROM (
        /// 
        ///  SELECT &apos;OINV&apos; &quot;Tabla&quot;, comp.&quot;ObjType&quot;, comp.&quot;DocEntry&quot;,&quot;DocNum&quot;,cli.&quot;LicTradNum&quot;  as &quot;Ruc&quot;,comp.&quot;CardName&quot;,comp.&quot;DocCur&quot;,comp.&quot;DocDate&quot;,comp.&quot;Indicator&quot; as Indicator,
        ///  case comp.&quot;Indicator&quot; when &apos;01&apos; then &apos;FACTURA&apos;
        ///  when &apos;03&apos; then &apos;BOLETA&apos;
        ///  when &apos;08&apos; then &apos;NOTA DEBITO&apos;
        ///  ELSE &apos;&apos; END AS &quot;TipoDocu [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EXX_COMPROBANTES_ELECTRONICOS {
            get {
                return ResourceManager.GetString("EXX_COMPROBANTES_ELECTRONICOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string EXX_RETENCION_DETALLE_FE {
            get {
                return ResourceManager.GetString("EXX_RETENCION_DETALLE_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;EXX_RETENCION_FE&quot;
        ///(
        /// IN DocEntry INT -- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN
        ///
        /// SELECT 
        /// IFNULL(T3.&quot;GlblLocNum&quot;, T4.&quot;TaxIdNum&quot;) as idEmisor,
        /// 20 as tipoDocumento,
        /// T0.&quot;U_EXX_SERIE_FE&quot; as Serie,
        /// T0.&quot;U_EXX_NUM_FE&quot;  as Correlativo,
        /// IFNULL(T3.&quot;GlblLocNum&quot;, T4.&quot;E_Mail&quot;) as correoEmisor,
        /// IFNULL(T2.&quot;E_Mail&quot;, &apos;&apos;) as correoAdquiriente,
        /// 
        /// 
        /// IFNULL(T0.&quot;U_EXX_SERIE_FE&quot;,&apos;&apos;)||&apos;-&apos;|| LPAD(ifnull(TO_VARCHAR(T0.&quot;U_EXX_NUM_FE&quot;),&apos;&apos;),8,&apos;0&apos;) as serieNumeroRetencion, 
        /// T [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EXX_RETENCION_FE {
            get {
                return ResourceManager.GetString("EXX_RETENCION_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///&quot;ZipCode&quot;,
        ///&quot;Building&quot;,
        ///&quot;County&quot;,
        ///&quot;City&quot;,
        ///(SELECT &quot;Name&quot; FROM OCST WHERE &quot;Code&quot; = T0.&quot;State&quot; AND &quot;Country&quot; = T0.&quot;Country&quot;) &quot;State&quot;,
        ///&quot;Street&quot;,
        ///&quot;IntrntAdrs&quot;
        ///FROM ADM1 T0.
        /// </summary>
        internal static string ObtenerADM1 {
            get {
                return ResourceManager.GetString("ObtenerADM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///TA.&quot;Indicator&quot; AS &quot;tipoDocumento&quot;,
        ///TA.&quot;FolioPref&quot; AS &quot;serieDocumento&quot;,
        ///TA.&quot;FolioNum&quot; AS &quot;correlativoDocumento&quot;,
        ///(CASE TA.&quot;DocCur&quot;
        ///WHEN &apos;PEN&apos; THEN TA.&quot;DocTotal&quot;
        ///ELSE TA.&quot;DocTotalFC&quot; 
        ///END) AS &quot;importeDocumento&quot;,
        ///(CASE TA.&quot;DocCur&quot;
        ///WHEN &apos;PEN&apos; THEN TF.&quot;DrawnSum&quot;
        ///ELSE TF.&quot;DrawnSumFc&quot; 
        ///END) AS totalAnticipos,
        ///(CASE TA.&quot;DocCur&quot;
        ///WHEN &apos;PEN&apos; THEN TF.&quot;Vat&quot;
        ///ELSE TF.&quot;VatFc&quot;
        ///END) AS &quot;totalIGVAncticipos&quot;,
        ///TO_NVARCHAR(TA.&quot;TaxDate&quot;, &apos;yyyy-MM-dd&apos;)
        ///FROM ODPI TA
        ///INNER JOIN {0} TF 
        ///ON TA.&quot;DocEntry&quot; = T [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtenerAnticipos {
            get {
                return ResourceManager.GetString("ObtenerAnticipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///&quot;U_EXA_TIPNCND&quot;,
        ///&quot;U_EXA_DESMOT&quot;
        ///FROM {0} T0, OADM T1
        ///WHERE &quot;DocEntry&quot; = {1}.
        /// </summary>
        internal static string ObtenerDatosAdicionalesEstela {
            get {
                return ResourceManager.GetString("ObtenerDatosAdicionalesEstela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        /// (SELECT &quot;Name&quot; FROM &quot;@EXT_NAVE&quot; A WHERE A.&quot;Code&quot; = &quot;U_EXT_NAVE&quot;) &quot;U_EXT_NAVE&quot;,
        /// &quot;U_EXT_CALLNUMBER&quot;,
        /// &quot;U_EXT_DESRESOLIDA&quot;,
        /// &quot;U_EXT_OSNRO&quot;,
        /// &quot;U_EXT_COMENTARIO&quot;,
        /// (SELECT &quot;Name&quot; FROM &quot;@EXT_MUELLE&quot; A WHERE A.&quot;Code&quot; = &quot;U_EXT_MUELLE&quot;) &quot;U_EXT_MUELLE&quot;,
        /// &quot;U_EXT_VIAJE&quot;,
        /// &quot;U_EXT_FECARRIBO&quot;,
        /// (SELECT &quot;Name&quot; FROM &quot;@EXT_LINEA&quot; A WHERE A.&quot;Code&quot; = &quot;U_EXT_LINEANAV&quot;) &quot;U_EXT_LINEANAV&quot;,
        /// &quot;U_EXT_RESPSOLIDA&quot;,
        /// &quot;U_EXT_dc_fact_VBWONbr&quot;, 
        /// T1.&quot;Phone1&quot;,
        /// T1.&quot;Fax&quot;
        ///FROM {0} T0, OADM T1
        ///WHERE &quot;DocEntry&quot; = {1}.
        /// </summary>
        internal static string ObtenerDatosAdicionalesPaperless {
            get {
                return ResourceManager.GetString("ObtenerDatosAdicionalesPaperless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///T1.&quot;U_EXX_TIPODOCU&quot; AS &quot;tipoIdentificacion&quot;,
        ///T1.&quot;LicTradNum&quot; AS &quot;numeroIdentificacion&quot;,
        ///T1.&quot;CardName&quot; AS &quot;nombre&quot;,
        ///(SELECT TOP 1 IFNULL(T2.&quot;Street&quot;,&apos;&apos;) || &apos; - &apos; || IFNULL(T2.&quot;County&quot;, &apos;&apos;) FROM CRD1 T2  WHERE T2.&quot;AdresType&quot; = &apos;B&apos; AND T2.&quot;CardCode&quot; = &apos;{0}&apos; AND T2.&quot;Address&quot; = &apos;{1}&apos;) AS &quot;direccionFiscal&quot;,
        ///&quot;E_Mail&quot; AS &quot;email&quot;,
        ///T1.&quot;Country&quot; AS &quot;codigoPais&quot;,
        ///IFNULL(T1.&quot;Phone1&quot;, &apos;&apos;) as &quot;telefono&quot;,
        ///IFNULL(T1.&quot;Fax&quot;, &apos;&apos;) as &quot;fax&quot;,
        ///T1.&quot;GlblLocNum&quot;,
        ///(SELECT TOP 1 IFNULL(T2.&quot;Street&quot;,&apos;&apos;) || &apos; - &apos; || IFNUL [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtenerDatosAdquiriente {
            get {
                return ResourceManager.GetString("ObtenerDatosAdquiriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        /// (CASE WHEN &quot;U_EXX_TIPEXP&quot; = &apos;00&apos; THEN &apos;N&apos; ELSE &apos;Y&apos; END) as &quot;documentoExportacion&quot;,
        /// (CASE WHEN (SELECT COUNT(*) FROM INV1 A WHERE A.&quot;DocEntry&quot; = T0.&quot;DocEntry&quot; AND A.&quot;TaxOnly&quot; = &apos;Y&apos;) &gt; 0 THEN &apos;0&apos; ELSE &apos;1&apos; END)as &quot;TransGratuita&quot;,
        /// &quot;CardCode&quot;,
        /// &quot;PayToCode&quot;,
        /// &quot;ShipToCode&quot;,
        /// &quot;DocType&quot;,
        /// &quot;Indicator&quot; as &quot;tipoComprobante&quot;,
        /// &quot;FolioPref&quot; as &quot;serie&quot;,
        /// &quot;FolioNum&quot; as &quot;correlativo&quot;,
        /// --Datos de referencia-----------------------------------------------------------------------------
        /// (CASE &quot;Indicator&quot; W [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtenerDatosCPE {
            get {
                return ResourceManager.GetString("ObtenerDatosCPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        /// T0.&quot;DocCur&quot;,
        /// T1.&quot;ItemCode&quot; as &quot;codigoArt&quot;,
        /// T1.&quot;AcctCode&quot; as &quot;descripcionServ&quot;,
        /// T1.&quot;Dscription&quot; as &quot;descripcion&quot;,
        /// T1.&quot;Quantity&quot; AS &quot;cantidadUnidades&quot;,
        /// (CASE WHEN IFNULL(T1.&quot;unitMsr&quot;, &apos;&apos;) = &apos;&apos; THEN &apos;UND&apos; ELSE T1.&quot;unitMsr&quot; END) as &quot;unidadMedidaSAP&quot;,
        /// IFNULL(T2.&quot;U_EXX_TIPOUMED&quot;, &apos;NIU&apos;) as &quot;unidadMedida&quot;,
        /// T1.&quot;Price&quot; AS &quot;valorUnitario&quot;,
        /// T1.&quot;PriceAfVAT&quot; AS &quot;precioUnitario&quot;,
        /// (CASE T0.&quot;DocCur&quot; WHEN &apos;SOL&apos; THEN T1.&quot;LineTotal&quot; WHEN &apos;PEN&apos; THEN T1.&quot;LineTotal&quot; ELSE T1.&quot;TotalFrgn&quot; END) AS &quot;valorI [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtenerDetalleDocumento {
            get {
                return ResourceManager.GetString("ObtenerDetalleDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        /// T0.&quot;DocCur&quot;,
        /// T1.&quot;ItemCode&quot; as &quot;codigoArt&quot;,
        /// T1.&quot;AcctCode&quot; as &quot;descripcionServ&quot;,
        /// T1.&quot;Dscription&quot; as &quot;descripcion&quot;,
        /// T1.&quot;Quantity&quot; AS &quot;cantidadUnidades&quot;,
        /// (CASE WHEN IFNULL(T1.&quot;unitMsr&quot;, &apos;&apos;) = &apos;&apos; THEN &apos;UND&apos; ELSE T1.&quot;unitMsr&quot; END) as &quot;unidadMedidaSAP&quot;,
        /// IFNULL(T2.&quot;U_EXX_TIPOUMED&quot;, &apos;NIU&apos;) as &quot;unidadMedida&quot;,
        /// T1.&quot;Price&quot; AS &quot;valorUnitario&quot;,
        /// T1.&quot;PriceAfVAT&quot; AS &quot;precioUnitario&quot;,
        /// (CASE T0.&quot;DocCur&quot; WHEN &apos;SOL&apos; THEN T1.&quot;LineTotal&quot; WHEN &apos;PEN&apos; THEN T1.&quot;LineTotal&quot; ELSE T1.&quot;TotalFrgn&quot; END) AS &quot;valorI [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ObtenerDetalleEstela {
            get {
                return ResourceManager.GetString("ObtenerDetalleEstela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &quot;CurrCode&quot;, &quot;CurrName&quot;, &quot;ISOCurrCod&quot; FROM OCRN
        ///.
        /// </summary>
        internal static string ObtenerMonedas {
            get {
                return ResourceManager.GetString("ObtenerMonedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTER PROCEDURE &quot;SMC_RETENCION_DETALLE_FE&quot;
        ///(
        /// IN DocEntry INT -- Error string to be displayed
        ///)
        ///LANGUAGE SQLSCRIPT AS
        ///BEGIN
        /// DECLARE FechaPago DATE;
        /// DECLARE TipoCambio DECIMAL;
        /// DECLARE TotalDocSinRet DECIMAL;
        /// 
        /// SELECT 
        /// &quot;TaxDate&quot; into FechaPago
        /// FROM &quot;OVPM&quot; T0 WHERE &quot;DocEntry&quot;=DocEntry;
        /// 
        /// select &quot;Rate&quot; into TipoCambio FROM &quot;ORTT&quot; WHERE &quot;Currency&quot;=&apos;USD&apos; and &quot;RateDate&quot;=FechaPago;
        /// 
        /// IF EXISTS (SELECT 1 FROM &quot;OVPM&quot; T0 
        ///      INNER JOIN &quot;VPM2&quot; T1 ON T0.&quot;DocEntry&quot; = T1.&quot;DocNum&quot;
        ///      WHERE  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SMC_RETENCION_DETALLE_FE {
            get {
                return ResourceManager.GetString("SMC_RETENCION_DETALLE_FE", resourceCulture);
            }
        }
    }
}
